### ISSUE TITLE
Add caching system to summoner based aggregation

### ISSUE THREAD

**Issue by lcontant** [software-space/qiyana-aggregator#25]
Currently, we work on a dumb aggregation with no caching based on previous requests. This extends the aggregation significantly.

We would need a system of caching that remembers the parameters with which the aggregation function has been called and skip the aggregation routine when executed with previously user arguments. The cache would have a TTL for matches and other warmer data.

**Comment by fastboyz** [comment]
Closing this as the new aggregation system takes care of this.
